version: '3.8'

services:
  xiaohongshu-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xiaohongshu-mcp
    restart: unless-stopped
    ports:
      - "18060:18060"
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
      # 如果需要代理，可以取消注释下面的行
      # - HTTP_PROXY=http://host.docker.internal:7890
      # - HTTPS_PROXY=http://host.docker.internal:7890
    volumes:
      # 持久化 cookies 数据
      - xiaohongshu_cookies:/app/cookies
      # 持久化其他数据
      - xiaohongshu_data:/app/data
      # 如果需要自定义配置文件，可以挂载
      # - ./config:/app/config:ro
    # 共享内存大小，Chrome 需要
    shm_size: 2gb
    # 安全选项
    security_opt:
      - seccomp:unconfined
    # 如果需要 GPU 加速（可选）
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - xiaohongshu_network
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# 数据卷
volumes:
  xiaohongshu_cookies:
    driver: local
  xiaohongshu_data:
    driver: local

# 网络
networks:
  xiaohongshu_network:
    driver: bridge
