version: '3.8'

services:
  xiaohongshu-mcp:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: xiaohongshu-mcp:latest
    container_name: xiaohongshu-mcp
    restart: unless-stopped
    ports:
      - "18060:18060"
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
      # 如果需要代理，可以取消注释下面的行
      - HTTP_PROXY=http://172.23.104.184:7890
      - HTTPS_PROXY=http://172.23.104.184:7890
    volumes:
      # 持久化 cookies 数据（映射到容器的临时目录）
      - ./xiaohongshu_cookies:/tmp
      # 持久化其他数据
      - ./xiaohongshu_data:/app/data
      # 如果需要自定义配置文件，可以挂载
      # - ./config:/app/config:ro
    # 共享内存大小，Chrome 需要
    shm_size: 2gb
    # 安全选项
    security_opt:
      - seccomp:unconfined
    # 如果需要 GPU 加速（可选）
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # networks:
    #   - xiaohongshu_network
    # 日志配置（开发环境）
    logging:
      driver: "json-file"
      options:
        max-size: "5m"        # 每个日志文件最大 5MB
        max-file: "5"         # 最多保留 5 个文件
        compress: "true"      # 压缩旧日志文件

# 数据卷
# volumes:
#   xiaohongshu_cookies:
#     driver: local
#   xiaohongshu_data:
#     driver: local

# 网络
# networks:
#   xiaohongshu_network:
#     driver: bridge
